(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(c-basic-offset 2)
 '(case-fold-search t)
 '(column-number-mode 1)
 '(compilation-ask-about-save nil)
 '(compilation-search-path (quote ("~/fbcode")))
 '(css-indent-level 2)
 '(current-language-environment "utf-8")
 '(default-frame-alist (quote ((left-fringe . 1) (right-fringe . 1) (vertical-scroll-bars) (menu-bar-lines . 0) (tool-bar-lines . 0) (font . "DejaVu Sans Mono-12"))))
 '(default-input-method "utf-8-prefix")
 '(default-major-mode (quote text-mode) t)
 '(display-buffer-reuse-frames nil)
 '(ecb-layout-name "left7")
 '(ecb-options-version "2.40")
 '(erc-auto-discard-away t)
 '(erc-auto-set-away t)
 '(erc-autoaway-idle-method (quote emacs))
 '(erc-autoaway-idle-seconds 600)
 '(erc-autoaway-mode t)
 '(erc-autojoin-channels-alist (quote (("tfbnw.net" "#perf" "#e" "#tupperware"))))
 '(erc-autojoin-domain-only t)
 '(erc-input-line-position -2)
 '(erc-nick "jallen")
 '(erc-nick-uniquifier "___")
 '(erc-port 6443)
 '(erc-public-away-p t)
 '(erc-server "irc.tfbnw.net")
 '(erc-try-new-nick-p t)
 '(erc-user-full-name "John Allen")
 '(espresso-indent-level 2)
 '(fill-column 78)
 '(flymake-no-changes-timeout 1)
 '(fringe-mode (quote (1 . 1)) nil (fringe))
 '(global-auto-revert-mode t)
 '(gud-gdb-command-name "gdb --annotate=1")
 '(ido-enable-flex-matching t)
 '(ido-everywhere t)
 '(ido-mode (quote buffer) nil (ido))
 '(indent-tabs-mode nil)
 '(large-file-warning-threshold nil)
 '(line-number-mode 1)
 '(mode-require-final-newline t)
 '(org-startup-folded (quote content))
 '(popwin:special-display-config (quote (("*grep*") ("*Help*") ("*Completions*" :noselect t) ("*Occur*" :noselect t))))
 '(py-basic-offset 4 t)
 '(remember-annotation-functions (quote (org-remember-annotation)))
 '(remember-handler-functions (quote (org-remember-handler)))
 '(show-paren-mode t nil (paren))
 '(split-height-threshold 10000)
 '(split-width-threshold 10000)
 '(transient-mark-mode t)
 '(use-dialog-box nil)
 '(use-file-dialog nil))


(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(flymake-errline ((((class color) (background dark)) (:background "DimGrey" :box nil))))
 '(isearch ((t (:background "blue" :foreground "white"))))
 '(lazy-highlight ((t (:background "yellow" :foreground "black")))))
